# This workflow will say hello to the world! :-)

name: Python application

on:
  push:
    branches: [ github_action_demo ]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: say_hello
      run: |
        python helloworld.py
